{"team":[
    {
        "name":"John",
        "occupation":"manager"
    },
    {
        "name":"Mike",
        "occupation":"technician"
    },
    {
        "name":"Sally",
        "occupation":"secretary"
    },
    {
        "name":"Bob",
        "occupation":"supervisor"
    },
    {
        "name":"Joe",
        "occupation":"consultant"
    }
]}